ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: lidar_link
    ignore_array: ""
    baudrate: 128000
    lidar_type: 1
    device_type: 0
    sample_rate: 5
    abnormal_check_count: 4
    fixed_resolution: false
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    support_motor_dir: true
    intensity: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 64.0
    range_min: 0.05
    frequency: 8.0
    invalid_range_is_inf: false
